### ISSUE TITLE
Set up another SN portal for development

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#583]
The production portal should only have production guides. No development work. 

The staging portal should be used as development purpose for guides, converter,  front-end, and even SN and quicklab update

**Comment by jakub-pomykala** [comment]
Implemented the same Open-Edx theme and also all the CSS and JS to run just like in the Production portal. However instead of CSS and JS to run from the cloud-hosted-guides prod branch we have set it up to temporarily run from my fork ([here](https://github.com/jakub-pomykala/cloud-hosted-guides?organization=jakub-pomykala&organization=jakub-pomykala)). This allows us to do quick changes to both files with out having to wait for Admins to review and merge PRs into prod.

**Comment by jakub-pomykala** [comment]
Things left to do till staging env is completed (in prioritised order):

- [x] Add all staging guides
- [x] Add SSO login
  - [x] Add all SSO buttons in courses admin portal (Do this by copying config from prod courses admin panel and set up in the exact same way) :
    - [x] Github
    - [x] Gmail
    - [x] LinkedIn
    - [x] IBMid
  - [x] Change providers settings to have two URIs (for both production site and staging site for redirections) : 
    - [x] Github
    - [x] Gmail
    - [x] LinkedIn
    - [x] IBMid
- [x] Remove staging guides from Prod env

**Comment by austin0** [comment]
Added SSO providers, need to set up new credentials so that they redirect to the staging environment.

**Comment by austin0** [comment]
Staging content has been removed from the prod portal.

Google/IBMid SSO needs fixing on the staging portal.

**Comment by austin0** [comment]
Google and IBMid SSO applications have been updated to accept `ol-staging` redirect urls.
